version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: postgres-hive
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hive-network
    platform: linux/arm64

  hive-metastore:
    image: bde2020/hive:latest
    container_name: hive-metastore
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_DB_URI: jdbc:postgresql://postgres:5432/metastore
      HIVE_METASTORE_DB_USER: hive
      HIVE_METASTORE_DB_PASS: hive
      SERVICE_PRECONDITION: "postgres:5432"
    volumes:
      - ../sqlite:/data
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml
    depends_on:
      - postgres
    networks:
      - hive-network
    command: "hive --service metastore"
    platform: linux/arm64

  hive-server:
    image: bde2020/hive:latest
    container_name: hive-server
    environment:
      HIVE_METASTORE_URIS: "thrift://hive-metastore:9083"
    volumes:
      - ../sqlite:/data
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml
    depends_on:
      - hive-metastore
    networks:
      - hive-network
    command: "hive --service hiveserver2"
    platform: linux/arm64

volumes:
  postgres-data:

networks:
  hive-network:
    driver: bridge
